language: ruby
before_install:
- rvm install 2.1.0-dev
- rvm use 2.1.0-dev


before_script:
- chmod +x ./script/cibuild

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
